Default: &defaults
  database: One.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: One_test.sqlite3
  <<: *defaults

Staging:
  database: One_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: One_production.sqlite3
  poolsize: 100
  <<: *defaults
